services:
  - type: web
    name: remix-eg
    env: node
    plan: free
    buildCommand: cd remix-eg && yarn install 
    startCommand: cd remix-eg && yarn start
    envVars:
      - key: DB_URL
        fromDatabase:
          name: elephant
          property: connectionString
    # scaling:
    #   minInstances: 1
    #   maxInstances: 1
    #   targetMemoryPercent: 60 # optional if targetCPUPercent is set
    #   targetCPUPercent: 60 # optional if targetMemory is set

databases:
  - name: elephant
    plan: free
    databaseName: mydb # optional (Render may add a suffix)
    user: adrian # optional
    ipAllowList:
      - source: 81.156.247.27
        description: home