services:
  - type: web
    name: remix-eg
    env: node
    buildCommand: yarn build
    startCommand: yarn start
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 60 # optional if targetCPUPercent is set
      targetCPUPercent: 60 # optional if targetMemory is set
  